require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AssignmentGradesController do

  # This should return the minimal set of attributes required to create a valid
  # AssignmentGrade. As you add validations to AssignmentGrade, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {  }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AssignmentGradesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all assignment_grades as @assignment_grades" do
      assignment_grade = AssignmentGrade.create! valid_attributes
      get :index, {}, valid_session
      assigns(:assignment_grades).should eq([assignment_grade])
    end
  end

  describe "GET show" do
    it "assigns the requested assignment_grade as @assignment_grade" do
      assignment_grade = AssignmentGrade.create! valid_attributes
      get :show, {:id => assignment_grade.to_param}, valid_session
      assigns(:assignment_grade).should eq(assignment_grade)
    end
  end

  describe "GET new" do
    it "assigns a new assignment_grade as @assignment_grade" do
      get :new, {}, valid_session
      assigns(:assignment_grade).should be_a_new(AssignmentGrade)
    end
  end

  describe "GET edit" do
    it "assigns the requested assignment_grade as @assignment_grade" do
      assignment_grade = AssignmentGrade.create! valid_attributes
      get :edit, {:id => assignment_grade.to_param}, valid_session
      assigns(:assignment_grade).should eq(assignment_grade)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AssignmentGrade" do
        expect {
          post :create, {:assignment_grade => valid_attributes}, valid_session
        }.to change(AssignmentGrade, :count).by(1)
      end

      it "assigns a newly created assignment_grade as @assignment_grade" do
        post :create, {:assignment_grade => valid_attributes}, valid_session
        assigns(:assignment_grade).should be_a(AssignmentGrade)
        assigns(:assignment_grade).should be_persisted
      end

      it "redirects to the created assignment_grade" do
        post :create, {:assignment_grade => valid_attributes}, valid_session
        response.should redirect_to(AssignmentGrade.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved assignment_grade as @assignment_grade" do
        # Trigger the behavior that occurs when invalid params are submitted
        AssignmentGrade.any_instance.stub(:save).and_return(false)
        post :create, {:assignment_grade => {  }}, valid_session
        assigns(:assignment_grade).should be_a_new(AssignmentGrade)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AssignmentGrade.any_instance.stub(:save).and_return(false)
        post :create, {:assignment_grade => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested assignment_grade" do
        assignment_grade = AssignmentGrade.create! valid_attributes
        # Assuming there are no other assignment_grades in the database, this
        # specifies that the AssignmentGrade created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AssignmentGrade.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => assignment_grade.to_param, :assignment_grade => { "these" => "params" }}, valid_session
      end

      it "assigns the requested assignment_grade as @assignment_grade" do
        assignment_grade = AssignmentGrade.create! valid_attributes
        put :update, {:id => assignment_grade.to_param, :assignment_grade => valid_attributes}, valid_session
        assigns(:assignment_grade).should eq(assignment_grade)
      end

      it "redirects to the assignment_grade" do
        assignment_grade = AssignmentGrade.create! valid_attributes
        put :update, {:id => assignment_grade.to_param, :assignment_grade => valid_attributes}, valid_session
        response.should redirect_to(assignment_grade)
      end
    end

    describe "with invalid params" do
      it "assigns the assignment_grade as @assignment_grade" do
        assignment_grade = AssignmentGrade.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AssignmentGrade.any_instance.stub(:save).and_return(false)
        put :update, {:id => assignment_grade.to_param, :assignment_grade => {  }}, valid_session
        assigns(:assignment_grade).should eq(assignment_grade)
      end

      it "re-renders the 'edit' template" do
        assignment_grade = AssignmentGrade.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AssignmentGrade.any_instance.stub(:save).and_return(false)
        put :update, {:id => assignment_grade.to_param, :assignment_grade => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested assignment_grade" do
      assignment_grade = AssignmentGrade.create! valid_attributes
      expect {
        delete :destroy, {:id => assignment_grade.to_param}, valid_session
      }.to change(AssignmentGrade, :count).by(-1)
    end

    it "redirects to the assignment_grades list" do
      assignment_grade = AssignmentGrade.create! valid_attributes
      delete :destroy, {:id => assignment_grade.to_param}, valid_session
      response.should redirect_to(assignment_grades_url)
    end
  end

end
